name: Run Tests and Upload Coverage
on: workflow_dispatch
permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: app/go.mod
          cache-dependency-path: app/go.sum
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go tool gotestsum --format-icons=hivis -- -coverprofile=coverage.txt ./...
      - name: Upload results to Codecov
        continue-on-error: true
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
